### ISSUE TITLE
Verify pymmcore-plus functionality on Squid microscope.

### ISSUE THREAD

**Issue by jeskesen** [czbiohub-sf/shrimPy#179]
This is the first test of the new engine on real hardware.  It has the same 2 cameras as Mantis, but a different stage.  There is also no DAQ to synchronize acquisition.

**Comment by ieivanov** [comment]
I think currently `shrimpy` is built to require a DAC, but that should not be the case. If a DAQ is not present - or if the user does not request hardware triggering, we should run the two acquisitions asynchronously - i.e. call 

```
lf_mmc.run_mda()
ls_mmc.run_mda()
```

Without worrying much if there is a time different on when they start or how long they take. Implementing this may require a change to the config file, for example adding 

```
time_settings:
  num_timepoints: 3
  time_interval_s: 5
  synchronize_acquisitions: True
```
